name: Analyze
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Download build wrapper
        run: wget "https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip"
      - name: Extract build wrapper
        run: unzip build-wrapper-linux-x86.zip
      - name: Install dependencies
        run: sudo apt-get install -y build-essential cmake libssl-dev nettle-dev libmbedtls-dev libacl1-dev libbz2-dev liblzma-dev liblz4-dev libzstd-dev lzop
      - name: Autogen
        run: ./build/ci/build.sh -a autogen
        env:
          BS: ${{ matrix.bs }}
      - name: Configure
        run: ./build/ci/build.sh -a configure
        env:
          BS: ${{ matrix.bs }}
          CRYPTO: ${{ matrix.crypto }}
      - name: Build
        run: build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw_output ./build/ci/build.sh -a build
        env:
          BS: ${{ matrix.bs }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
